USE DRECARGAS_APUESTATOTAL;


CALL SP_INSERTAR_CANAL_COMUNICACION('WhatsApp');
CALL SP_INSERTAR_CANAL_COMUNICACION('TeleGram');

INSERT INTO ROL (ID_ROL, NOMBRE_ROL, ESTADO) VALUES (NULL, 'PROMOTOR VENTAS', 1);
INSERT INTO ROL (ID_ROL, NOMBRE_ROL, ESTADO) VALUES (NULL, 'SUPERVISOR', 1);
INSERT INTO ROL (ID_ROL, NOMBRE_ROL, ESTADO) VALUES (NULL, 'CLIENTE', 1);


CALL SP_INSERTAR_USUARIO_PERSONA('promotor_ventas_1', 'p0LgEdvemAY8g', 'Jose', 'Aguirre', 'Quispe', '78954123', '912554876', '1');
CALL SP_INSERTAR_USUARIO_PERSONA('msk', 'p0g3GKQMW.SpY', 'Msk', 'Msk', 'Msk', '78541236', '915468573', '3');

INSERT INTO TIPO_TRANSACCION (ID_TIPO_TRANSACCION, NOMBRE_TIPO_TRANSACCION, ESTADO) VALUES (NULL, 'DEPOSITO BANCARIO', 1);
INSERT INTO TIPO_TRANSACCION (ID_TIPO_TRANSACCION, NOMBRE_TIPO_TRANSACCION, ESTADO) VALUES (NULL, 'TRANSFERENCIA BANCARIA', 1);
INSERT INTO TIPO_TRANSACCION (ID_TIPO_TRANSACCION, NOMBRE_TIPO_TRANSACCION, ESTADO) VALUES (NULL, 'PAGO AGENTE', 1);

INSERT INTO BANCO (ID_BANCO, NOMBRE_BANCO, ESTADO) VALUES (NULL, 'BANCO DE LA NACION', 1);
INSERT INTO BANCO (ID_BANCO, NOMBRE_BANCO, ESTADO) VALUES (NULL, 'BANCO DE CREDITO', 1);
INSERT INTO BANCO (ID_BANCO, NOMBRE_BANCO, ESTADO) VALUES (NULL, 'BBVA', 1);
INSERT INTO BANCO (ID_BANCO, NOMBRE_BANCO, ESTADO) VALUES (NULL, 'INTERBANK', 1);

CALL SP_INSERTAR_RECARGA_TRANSACCION('CP001', 90.25, '2', '1', '2', 'sadfgdsafgdsadfgdsa', '2023-01-31 11:38:02', '78541236', '1', '');