CREATE DATABASE IF NOT EXISTS DRECARGAS_APUESTATOTAL;

USE DRECARGAS_APUESTATOTAL;

CREATE TABLE IF NOT EXISTS CANAL_COMUNICACION (
    ID_CANAL_COMUNICACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CANAL_COMUNICACION VARCHAR(255) NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS HIST_CANAL_COMUNICACION (
    ID_HIST_CANAL_COMUNICACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CANAL_COMUNICACION INT NOT NULL,
    NOMBRE_CANAL_COMUNICACION VARCHAR(255) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT NULL,
    FECHA_MODIFICACION DATETIME DEFAULT NULL,
    FECHA_ELIMINACION DATETIME DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_CANAL_COMUNICACION) REFERENCES CANAL_COMUNICACION (ID_CANAL_COMUNICACION)
);

CREATE TABLE IF NOT EXISTS PERSONA (
    ID_PERSONA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PERSONA VARCHAR(255) NOT NULL,
    APELLIDO_PATERNO_PERSONA VARCHAR(255) NOT NULL,
    APELLIDO_MATERNO_PERSONA VARCHAR(255) NOT NULL,
    DNI_PERSONA VARCHAR(9) NOT NULL UNIQUE,
    TELEFONO_PERSONA VARCHAR(9) NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS HIST_PERSONA (
    ID_HIST_PERSONA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    NOMBRE_PERSONA VARCHAR(255) NOT NULL,
    APELLIDO_PATERNO_PERSONA VARCHAR(255) NOT NULL,
    APELLIDO_MATERNO_PERSONA VARCHAR(255) NOT NULL,
    DNI_PERSONA VARCHAR(9) NOT NULL,
    TELEFONO_PERSONA VARCHAR(9) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT NULL,
    FECHA_MODIFICACION DATETIME DEFAULT NULL,
    FECHA_ELIMINACION DATETIME DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE IF NOT EXISTS ROL (
    ID_ROL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ROL VARCHAR(255) NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_USUARIO VARCHAR(255) NOT NULL,
    ID_PERSONA INT NOT NULL,
    ID_ROL INT NOT NULL,
    MOTIVO_BAJA VARCHAR(255) DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
    FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE IF NOT EXISTS HIST_USUARIO (
    ID_HIST_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOMBRE_USUARIO VARCHAR(255) NOT NULL,
    PASSWORD_USUARIO VARCHAR(255) NOT NULL,
    ID_PERSONA INT NOT NULL,
    ID_ROL INT NOT NULL,
    MOTIVO_BAJA VARCHAR(255) DEFAULT NULL,
    FECHA_CREACION DATETIME DEFAULT NULL,
    FECHA_MODIFICACION DATETIME DEFAULT NULL,
    FECHA_ELIMINACION DATETIME DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
    FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE IF NOT EXISTS BILLETERA_VIRTUAL (
    ID_BILLETERA_VIRTUAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SALDO_BILLETERA_VIRTUAL DECIMAL(20, 2) NOT NULL,
    ID_USUARIO INT NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS HIST_BILLETERA_VIRTUAL (
    ID_HIST_BILLETERA_VIRTUAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_BILLETERA_VIRTUAL  INT NOT NULL,
    SALDO_BILLETERA_VIRTUAL DECIMAL(20, 2) NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT NULL,
    FECHA_MODIFICACION DATETIME DEFAULT NULL,
    FECHA_ELIMINACION DATETIME DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_BILLETERA_VIRTUAL) REFERENCES BILLETERA_VIRTUAL (ID_BILLETERA_VIRTUAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS TIPO_TRANSACCION (
    ID_TIPO_TRANSACCION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO_TRANSACCION VARCHAR(255) NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS BANCO (
    ID_BANCO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_BANCO VARCHAR(255) NOT NULL,
    ESTADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RECARGA_TRANSACCION (
    ID_RECARGA_TRANSACCION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COD_PAGO_RECARGA_TRANSACCION VARCHAR(255) NOT NULL,
    SALDO_RECARGA_TRANSACCION  DECIMAL(20, 2) NOT NULL,
    ID_BANCO INT NOT NULL,
    ID_TIPO_TRANSACCION INT NOT NULL,
    ID_CANAL_COMUNICACION INT NOT NULL,
    VOUCHER_RECARGA_TRANSACCION LONGBLOB NOT NULL,
    FECHA_OPERACION_RECARGA_TRANSACCION DATETIME NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_USUARIO_REGISTRANTE INT NOT NULL,
    OBSERVACION_RECARGA_TRANSACCION VARCHAR(255) DEFAULT NULL,
    MOTIVO_BAJA VARCHAR(255) DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_BANCO) REFERENCES BANCO (ID_BANCO),
    FOREIGN KEY (ID_TIPO_TRANSACCION) REFERENCES TIPO_TRANSACCION (ID_TIPO_TRANSACCION),
    FOREIGN KEY (ID_TIPO_TRANSACCION) REFERENCES TIPO_TRANSACCION (ID_TIPO_TRANSACCION),
    FOREIGN KEY (ID_CANAL_COMUNICACION) REFERENCES CANAL_COMUNICACION (ID_CANAL_COMUNICACION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS HIST_RECARGA_TRANSACCION (
    ID_HIST_RECARGA_TRANSACCION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_RECARGA_TRANSACCION INT NOT NULL,
    COD_PAGO_RECARGA_TRANSACCION VARCHAR(255) NOT NULL,
    SALDO_RECARGA_TRANSACCION  DECIMAL(20, 2) NOT NULL,
    ID_BANCO INT NOT NULL,
    ID_TIPO_TRANSACCION INT NOT NULL,
    ID_CANAL_COMUNICACION INT NOT NULL,
    VOUCHER_RECARGA_TRANSACCION LONGBLOB NOT NULL,
    FECHA_OPERACION_RECARGA_TRANSACCION DATETIME NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_USUARIO_REGISTRANTE INT NOT NULL,
    OBSERVACION_RECARGA_TRANSACCION VARCHAR(255) DEFAULT NULL,
    MOTIVO_BAJA VARCHAR(255) DEFAULT NULL,
    FECHA_CREACION DATETIME DEFAULT NULL,
    FECHA_MODIFICACION DATETIME DEFAULT NULL,
    FECHA_ELIMINACION DATETIME DEFAULT NULL,
    ESTADO INT NOT NULL,
    FOREIGN KEY (ID_RECARGA_TRANSACCION) REFERENCES RECARGA_TRANSACCION (ID_RECARGA_TRANSACCION),
    FOREIGN KEY (ID_BANCO) REFERENCES BANCO (ID_BANCO),
    FOREIGN KEY (ID_TIPO_TRANSACCION) REFERENCES TIPO_TRANSACCION (ID_TIPO_TRANSACCION),
    FOREIGN KEY (ID_TIPO_TRANSACCION) REFERENCES TIPO_TRANSACCION (ID_TIPO_TRANSACCION),
    FOREIGN KEY (ID_CANAL_COMUNICACION) REFERENCES CANAL_COMUNICACION (ID_CANAL_COMUNICACION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);